### ISSUE TITLE
server

### ISSUE THREAD

**Issue by reformc** [themeyic/go-dlt645#1]
你好，可以做server用吗？就是模拟电表设备。

**Comment by themeyic** [comment]
都可以的

**Comment by themeyic** [comment]
这个包是从设备里面读取报文,然后按照dlt645协议解析得到相应属性的数据，所以不能模拟电表设备哦

**Comment by alvaromemo** [comment]
Hi @themeyic. This protocol is relate it to dlt645/97 or dlt645/2007.
