### ISSUE TITLE
在windows下会报错

### ISSUE THREAD

**Issue by reformc** [themeyic/go-dlt645#2]
github.com\goburrow的serial包在windows下的open函数是错误的，可以参考下github.com\tarm\goserial的serial包

**Comment by themeyic** [comment]
我修复一下

**Comment by themeyic** [comment]
这是因为校验码没有动态计算出来，现在可以了

**Comment by themeyic** [comment]
这个包在linux/mac os和windows下面都是没有问题的，可能是你的格式不对，要按照例子里面的格式来哦
